//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFapp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullStudentList
    {
        public string Name { get; set; }
        public string SureName { get; set; }
        public string Group { get; set; }
        public Nullable<int> Grade { get; set; }
    }
}
